### ISSUE TITLE
NBA Datasets Download Links are Broken 

### ISSUE THREAD

**Issue by urbaneman** [nttcom/WASB-SBDT#7]
Hi, there, thanks for your nice work.

I attempted to download the NBA basketball datasets. However, all the download links seem to be broken. [NBA Dataset](https://ruiyan1995.github.io/SAM.html)
I contacted the author and hadn't received a reply. Can you share the data with me?
I will follow the License of the original data, btw, the corresponding zip code. 

Thank you.

**Comment by urbaneman** [comment]
the datasets owner answered me.

**Comment by walternat1ve** [comment]
@urbaneman any idea where to get the "ball-annos" from? it doesnt seem to be included in the dataset :thinking:
